### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by gs-akhan** [zinserjan/shim-loader#3]
ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve module 'shim-loader' in /usr/local/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:0-116 1:0-116

Thanks

**Comment by zinserjan** [comment]
Module is missing.  Install it with  `npm install shim-loader --save-dev`.
