### ISSUE TITLE
webpack DeprecationWarning

### ISSUE THREAD

**Issue by devthejo** [zinserjan/shim-loader#4]
Hello, first thanks for this tool,

when I

    $ webpack --watch

I get this error:

    Webpack is watching the files…

    (node:11587) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
    parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    Hash: c8841bd4f2aab718b111
    Version: webpack 2.5.1

**Comment by zinserjan** [comment]
Thanks for reporting. Released the fix as 1.0.0.
